### ISSUE TITLE
Higher quality/bitrate downloads and More metadata included in song file.

### ISSUE THREAD

**Issue by superstarx** [th-ch/youtube-music#1010]
I have noticed that the song downloads are at a bitrate of 124 kbps, by both listening and looking at the properties of song files. The low quality is very noticeable when listening to it, and I wondered if it is possible to adjust the audio quality that you download with? I am not sure if this is already possible or not, since I cannot find any setting corresponding with it. This is mostly based on personal preference but it would be nice to have the songs be at the higher bitrates. 
![image](https://user-images.githubusercontent.com/119865271/215533909-5367a936-94f7-4dd6-8263-d158a3a9d3b4.png)

Adding to this, there is also barely any metadata for the song, most importantly which album a song is from. It is of course a small thing but I would appreciate the metadata to be better, if possible. (example of what I mean below, no album is specified)
![image](https://user-images.githubusercontent.com/119865271/215535360-65eff8e8-d3fd-4793-bac6-cb1c99219289.png)
The album being included in the metadata can, for example, make it easier to listen to an album in an app like Musicolet or just Windows media player.

Please excuse any grammatical mistakes or if these issues are known, English is not my mother tongue and I'm new to this 😄 .

**Comment by MasamuneDate99** [comment]
Didn't know about the metadata from album, but the bitrate problem related to youtube itself. As you may aware that youtube have "Premium" options. On regards to regular youtube, it doesn't have any problem aside from ads. But on Youtube music, it makes a significant problem on the aspect of the audio quality. You can only have a "Normal" quality without premium, and unlocked the High quality with youtube premium.

Youtube premium itself offer a 320kbps bitrate of audio ( CMIIW ), if you are looking for a high quality bitrate ( hi-fi / lossless ) spotify is the answer since it provide a 1k bitrate audio. And maybe related to the problem is the source of the songs, as you may know that youtube let everyone upload their thing, maybe the author doesn't have a high quality audio file either, and we still haven't count the youtube audio compression method.

**Comment by ZhiTang92** [comment]
You can download as opus, maybe will get better quality.
![螢幕擷取畫面 (114)](https://user-images.githubusercontent.com/102956763/217303584-5f3a1af7-6e85-4edf-80b5-859b504456f7.png)

**Comment by LetrixZ** [comment]
You will be limited to 'Normal' quality for downloads with has a maximum of 128Kbps/160Kbps.

Here is the report YT-DL gives for formats:

Without `--cookies`:
```
599 m4a   audio only      2 │  852.57KiB  31k https │ audio only       mp4a.40.5   31k 22k ultralow, m4a_dash
600 webm  audio only      2 │  907.59KiB  33k https │ audio only       opus        33k 48k ultralow, webm_dash
139 m4a   audio only      2 │    1.32MiB  49k https │ audio only       mp4a.40.5   49k 22k low, m4a_dash
249 webm  audio only      2 │    1.31MiB  48k https │ audio only       opus        48k 48k low, webm_dash
250 webm  audio only      2 │    1.74MiB  64k https │ audio only       opus        64k 48k low, webm_dash
140 m4a   audio only      2 │    3.49MiB 130k https │ audio only       mp4a.40.2  130k 44k medium, m4a_dash
251 webm  audio only      2 │    3.46MiB 128k https │ audio only       opus       128k 48k medium, webm_dash
```

With `--cookies`:
```
599 m4a   audio only      2 │  852.57KiB  31k https │ audio only       mp4a.40.5   31k 22k ultralow, m4a_dash
600 webm  audio only      2 │  907.59KiB  33k https │ audio only       opus        33k 48k ultralow, webm_dash
139 m4a   audio only      2 │    1.32MiB  49k https │ audio only       mp4a.40.5   49k 22k low, m4a_dash
249 webm  audio only      2 │    1.31MiB  48k https │ audio only       opus        48k 48k low, webm_dash
250 webm  audio only      2 │    1.74MiB  64k https │ audio only       opus        64k 48k low, webm_dash
140 m4a   audio only      2 │    3.49MiB 130k https │ audio only       mp4a.40.2  130k 44k medium, m4a_dash
251 webm  audio only      2 │    3.46MiB 128k https │ audio only       opus       128k 48k medium, webm_dash
141 m4a   audio only      2 │    6.95MiB 258k https │ audio only       mp4a.40.2  258k 44k high, m4a_dash
```

251: Opus 128k "Normal" quality.
141: AAC 258Kbps "High" quality, only for premium users.

Ideally, the `downloader` plugin should use your cookies to download in the best quality possible but as far as I know, it is not possible to retrieve them.

**Comment by anthony75smith75** [comment]
I agree with your findings. The Download plugin does not seem to pick up premium users cookies and allow the higher bit rate m4a at 256k. I found a work around using "4K Video Downloader" which allows one to properly log in to YouTube. Under "Extract audio - m4a", we can find the High 256k version. I have actually compared the audio quality using some frequency spectrum graph software called Faking the Funk. The results are quite surprising.

**Comment by anthony75smith75** [comment]
Here are some screen shots of the very interesting results:

![yt opus](https://user-images.githubusercontent.com/77678231/219999098-d4c5ac72-58e1-4cc2-8399-edf0829edd2c.jpg)


Opus does a good job at 128k with strong white line and reaches 20khz frequency which is important since that is essentially the extent of human hearing.

![yt m4a 256](https://user-images.githubusercontent.com/77678231/219999144-90b02ca2-a077-4921-86a6-ee7a8bbc609e.jpg)

AAC/M4A at 256k extends above 20khz and attempts to reach CD quality at 22khz but the white line is significantly dropped. This is a poor encode with lots of wiped out sound represented by black space. What is Google doing wrong?

![Tital](https://user-images.githubusercontent.com/77678231/219999171-eba69610-201c-4300-aa15-b621cd24eb3d.jpg)

This source is the same song from Tital. I downloaded FLAC and encoded to m4a 256k using ffMpeg for proper and equal comparison to above. Notice solid strong white line and very high frequency near CD quality sound. This is what we should also be getting from YouTube Music.

Guess this is one of the reasons YouTube is known for poor sound quality and why they don't seem to advertise the 256k High Quality audio much. Quite disappointed with Google on this one. Maybe it's better just to stick with the Opus at this stage until they fix the m4a 256k encodes.

**Comment by Araxeus** [comment]
We initially download opus then convert it to mp3 using ffmpeg

* 124 kbps is actually the highest mp3 kbps you get from that process

* opus is converted to mp3 because id3/metadata tags can only be written to mp3 files currently

**Comment by Araxeus** [comment]
I've opened a PR which will add the album field to downloads (when available)

And will add the trackId (`#`) if downloading an album

keep in mind that it will only work with mp3 files, like stated in my comment above
