### ISSUE TITLE
Copyright/legal issues with branding

### ISSUE THREAD

**Issue by nsde** [th-ch/youtube-music#1034]
Hello,
I'm not a lawyer or anything, but just wanted to give some advice:
I think you shouldn't use the YouTube Music logo and branding everywhere.

I know, it maybe seems like it is too late to change everything now, but just look [what happened to YouTube Vanced](https://droidmaze.com/youtube-vanced-discontinued-due-to-legal-reasons/).

This project is great, but sadly it's just a matter of time when this project will face legal action by Google.

Best regards

**Comment by Zo-Bro-23** [comment]
Likely why [YTMD](https://github.com/ytmdesktop/ytmdesktop) uses a different logo. Technically the app doesn't infringe on any of Google's code. We only add plugins on _top_ of Google's code. Obviously if Google wants to take us down they'll find a way, so changing the logo might be a safe bet.

**Comment by Araxeus** [comment]
Youtube Vanced got into problems because they distributed a modified YouTube apk

Look at revanced - they don't publish the modified apk, they only publish the patches that you need to apply yourself

This app is not a modified official client, just a free wrapper around the official web app

so I think the chances of legal actions on this app are very slim
