### ISSUE TITLE
Media keys not working

### ISSUE THREAD

**Issue by maegull** [th-ch/youtube-music#1166]
The only reason why I'm not using this app is because it doesn't work with my media keys. I can't just skip a song while in a game I have to go all the way out and skip it manually instead of just pushing FN+F12. I'm not sure if there's any way to fix this but if there is I would very much appreciate it if someone told me or helped me through this.

**Comment by DmitriySalnikov** [comment]
I just ran into a similar problem again.
I tried restarting the program, disabling plug-ins and running as administrator...
It turned out that my browser just took full control of these buttons, while he did not switch anything himself. I reloaded the YouTube tab in the browser and this app started switching tracks again when pressing the multimedia buttons.

However, these are the side mouse buttons configured as multimedia buttons, but I think the essence is the same.

**Comment by gianfj** [comment]
It seems that's caused by chrome locking the media keys.
Setting "chrome://flags/#hardware-media-key-handling" to disabled made the keys to work again.

**Comment by DereC4** [comment]
Is this issue resolved then?

**Comment by gianfj** [comment]
Hi @DereC4 

Yes, the issue is with Chrome, not with youtube-music.

**Comment by DereC4** [comment]
I actually was not aware we could skip with shortcuts, I always just right clicked from the taskbar 

![image](https://github.com/th-ch/youtube-music/assets/53978637/30dab245-91be-4cf1-93b8-2c464a795c48)

**Comment by Andrew15-5** [comment]
This shouldn't be closed since the fix isn't implemented yet. I tried https://github.com/th-ch/youtube-music/releases/tag/v2.0.2 and it still doesn't work. I've tried all 4 variations of boolean switches:

```json
		"shortcuts": {
			"enabled": true,
			"overrideMediaKeys": true,
			"global": {
				"previous": "XF86AudioPrev",
				"playPause": "XF86AudioPlay",
				"next": "XF86AudioNext"
			}
		},
```

The only thing that worked (with the app in background) are custom keys that are not bound by the OS, e.g., "Ctrl+H", "Ctrl+J", "Ctrl+L".

**Comment by JellyBrick** [comment]
Duplicated of #647

**Comment by tejonaco** [comment]
for me media keys aren't working either, they work fine with sportify or AIMP app.
