### ISSUE TITLE
Fixes for 1.20 issues in one place to help out folks.

### ISSUE THREAD

**Issue by MycPimp** [th-ch/youtube-music#1208]
If you're experiencing severe lag or playback issues in the app, switch the adblocker mode from "blocklists" to "in player", and if that doesn't fix it, try turning off ad block completely if you already have a premium account or don't care about ads.

If you don't see an image in your player, turn off the bypass age restriction feature.

Some users are also reporting that they fixed longterm memory leaks by turning off genius lyrics.

There are also currently more issues I haven't seen a fix for, such as the image resolution for music cover art being very low or missaligned, and the new version of the youtube music app just, lacks an actual back button?

**Comment by AkaHusky24** [comment]
THANK YOU SO MUCH, you saved me with the image in player fix

**Comment by Shadowphoenix** [comment]
Since Jelly referenced this in my Ticket, im gonna reverse-reference myself here: i did not have Adblocker nor other modules enabled and it still lagged like hell. Disabling Hardwareacceleration fixed the lag, seemingly even after enabling Adblock (or at least if Adblock reintroduced some hanging, i do not notice it).

So if disabling Adblock doesnt fix it for you guys, try disabling Hardwareacceleration.

**Comment by JellyBrick** [comment]
If still having trouble, check this out: #1254
