### ISSUE TITLE
app is unusable recent version !!

### ISSUE THREAD

**Issue by markonop93** [th-ch/youtube-music#1226]
bigger leaks than when Kakhovka dam was blown. Windows is dying from memory overload

no fix comes ??

**Comment by symonxdd** [comment]
Can you please specify the problem you are facing? A screenshot perhaps? Since when did the alleged 'memory leaks' start happening? What version is your app?

**Comment by Traace** [comment]
After 3-5 hours of listening the music randomly freezes and the application begins to lag, meanwhile it is using way more RAM than it should. My guess is the streams fill up RAM over time, but it never gets cleared. Restarting the application fixes the issue, again just for a few hors.

Memory Leaks currently occure on both Windows (X86_64) and MacOS (ARM64) for me. Version is v1.20.0

**Comment by JellyBrick** [comment]
#1208

**Comment by symonxdd** [comment]
@markonop93

'it said "recent version".. newest'

You must be new developer forums, because that's not the way to describe your issue. How should I possibly know what version you were using the time of writing? Should I check the date on which you posted and go research what version that was for the time period? Next time, think a little more before arrogantly commenting to a community member who wants to help. Pajacu.

**Comment by symonxdd** [comment]
@markonop93

> it said "recent version".. newest

You must be new to developer forums, because that's not the way to describe your issue.

How should I possibly know what version you were using at the time of writing? Should I check the date on which you posted and go research what version that was for the time period? Next time, think a little more before arrogantly commenting to a community member who wants to help. Pajacu.
