### ISSUE TITLE
Taking Too Much CPU Usage!

### ISSUE THREAD

**Issue by yoyosingh123** [th-ch/youtube-music#1227]
Hey can you please let me know how can I optimize the app so It takes less CPU usage I'm a gamer and I love listening to music in background but It's taking some of my FPS, I'm using default settings but is there anything I can Enable/Disable to make it only use like 100 MB of memory If possible.

**Comment by Zack-Heisnberg** [comment]
currently the usage is optimized , it's okay to see some spikes from time to time i get as low as 0.1/100 cpu usage on my device when it's simply playing , and for memory only about 300mb , please note that the app use ElectronJS ( chrome + nodejs ) so that should take more then 100mb in almost any situation

**Comment by Jeluxe** [comment]
The app take like 15-18% cpu and i have this CPU (Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz   3.40 GHz) 
so i think it is optimization problem
