### ISSUE TITLE
Sign-in security

### ISSUE THREAD

**Issue by RobertBell96** [th-ch/youtube-music#130]
signed into my google account and got a notification (via email) asking if i had signed in with a mac (i am on pc)

**Comment by th-ch** [comment]
Hey @RobertBell96, thanks for the feedback! This is not surprising, the app forces the [user-agent](https://github.com/th-ch/youtube-music/blob/644950ccc0d446ee7c2c230ea05e7d27877358ea/index.js#L158) for login (otherwise, you might get a "Browser not supported" error when trying to log in) and this artificial user-agent simulates a Mac device.

Hope that answers your question! If needed to go further, an advanced option to specify a custom user-agent could be specified.

**Comment by RobertBell96** [comment]
thats great thanks :) i uninstalled and changed password just to be on the safe side till you got back to me. Now i know it is safe i will deffinatly download it again.. :) thank you!!!
