### ISSUE TITLE
[Feature request] dropdown search history

### ISSUE THREAD

**Issue by jrabinow** [th-ch/youtube-music#162]
When clicking in the search bar, it would be nice to have the last search queries unroll as a dropdown (say 5 or 10 or so). Bonus: auto-filtering of the historical queries as letters are typed

**Comment by Araxeus** [comment]
Youtube Music has this feature enabled by default, maybe you created this issue before they updated it?
Right now it works exactly as you described - filtering included
![01-04-2021 16 06 00](https://user-images.githubusercontent.com/78568641/113298334-61821780-9304-11eb-8fda-69178bdeef93.png)

**Comment by jrabinow** [comment]
Hmm, weird. I don't have that on my end. Maybe it's a partial rollout of a new feature?

**Comment by Bellisario** [comment]
@jrabinow what language are you using, and are you using a Google Account or not?
I'm asking you this because in some countries can be disabled or, if you are using a Google account with YouTube history disabled, here is your problem.

P.S.: This functionality is already active for a long time, I don't think this is your problem.

**Comment by jrabinow** [comment]
@Bellisario it looks like I had paused search history a long time ago and forgotten about it. I can confirm that turning search history back on fixes the problem. Thank you!
