### ISSUE TITLE
[Feature Request] Disable Autoplay

### ISSUE THREAD

**Issue by mavzolej** [th-ch/youtube-music#171]
Would be great to have the possibility of disabling autoplay — in case the user just wants to listen a single song / album found through search without going into "the radio mode" afterwards.

**Comment by th-ch** [comment]
Hey @mavzolej, thanks for the feedback! https://github.com/th-ch/youtube-music/commit/eaa957168ff015157efc62887c8f45bdfac262d4 adds a plugin to disable autoplay and will ship in the next version! You'll just need to enable that plugin and it is advised to disable the "autoconfirm when paused" plugin (it can interfere by playing the videos despite autoplay being disabled).

**Comment by mavzolej** [comment]
> Hey @mavzolej, thanks for the feedback! [eaa9571](https://github.com/th-ch/youtube-music/commit/eaa957168ff015157efc62887c8f45bdfac262d4) adds a plugin to disable autoplay and will ship in the next version! You'll just need to enable that plugin and it is advised to disable the "autoconfirm when paused" plugin (it can interfere by playing the videos despite autoplay being disabled).

Thanks, great news! Waiting for it.

**Comment by senhalil** [comment]
Thanks for the amazing work! Don't know if it is voluntary or a bug but here is my observations about the disable-autoplay. 

When the url is modified to be a list -- e.g., `"url": "https://music.youtube.com/watch?list=RDAMVM4AJtgsl8fRk",` -- without disable-autoplay everything works as expected but when it is enabled, next/previous buttons pause the song (after going to the next/previous song).

`disable-autoplay: false` (everything works as expected)
- **at app launch:** the first song of the list starts playing automatically
- **next/previous buttons:** goes to next/previous (or the beginning of the current) song and starts playing the song
- **end of the current song is reached:** the next song from the list starts playing
- **end of the list/album has reached:** autoplay adds a similar song to the end of the queue automatically and continues playing (unless Autoplay is toggled from the UX) 

`disable-autoplay: true`
- **at app launch:** the first song doesn't play automatically (_expected_)
- **next/previous buttons:** goes to next/previous (or the beginning of the current) song but doesn't continue playing the song (_unexpected_, I assume)
- **end of the current song is reached:** the next song from the list starts playing (_expected_, I assume)
- **end of the album has reached:** autoplay is shows to be ON on the interface and it adds a similar song to the end of the queue automatically but it is not played (the fact that another song is not played is _expected_ but autoplay shown to be ON and  another song being added to the queue are _unexpected_, imo. This is a problem because when a new song is added to a list by autoplay, the `list` and `v` parameters of the URL are modified automatically, even if the song is not played and when the app is restarted, the list is not the same list anymore)

My expectation was when autoplay is disabled (`disable-autoplay: true`)
- next/previous buttons do go to the next/previous song and mimic the state before the button press -- i.e., if a song was playing when the user hit next button, then the player goes to the next song and starts playing, if we the current song was paused when the next button is hit, then the player goes to the next song but doesn't play the song.
- when the end of an album/list is reached, the player stops at the end of the last song of the list (this is the behaviour if the Autoplay toggle is disabled on the UX)
