### ISSUE TITLE
[Bug]: Album cover is not centred on larger screens

### ISSUE THREAD

**Issue by makisukurisu** [th-ch/youtube-music#1781]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.2.0

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official YTM web version](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11 22H2 22621.3155

### What CPU architecture are you using?

x64

### Reproduction steps

1. Get a “large” monitor (in my case — 2560×1440 with 100% scaling) (this is important)
2. Open the app in full-screen with a taskbar of regular size (48 px)
3. Open any song (for example — [this one](https://music.youtube.com/watch?v=URzOGF_QGls)) with an album cover that is (preferably) 1:1.

### Expected Behavior

The album cover is centred both, vertically and horizontally, as it is on the official website:

![image](https://github.com/th-ch/youtube-music/assets/49622129/22c1279a-74cc-49f1-ac2a-42ab60662418)

*I've made the background red, so you can see where the album cover is located clearly

### Actual Behavior

The album cover is "sticking" to the top of the available space:
![image](https://github.com/th-ch/youtube-music/assets/49622129/58b7c27e-e7b6-4655-993b-17821e5cbbb3)

Which doesn't happen on a smaller screen (by height), i.e - 1920x1080 px:
![image](https://github.com/th-ch/youtube-music/assets/49622129/9a63def8-c7ff-4af1-9440-6be3a7942575)

### Enabled plugins

Any, or none.
Here's an example with all plugins disabled:
![image](https://github.com/th-ch/youtube-music/assets/49622129/f2fdf6f5-e708-4b19-bd0b-a4cd5727ae40)

But I use a lot of them, including, but not limited to:
- Ambient Mode
- Album Cover Theme
- Exponential Volume
- In-App Menu
- Navigation
- etc

See, the following image, if necessary:

![image](https://github.com/th-ch/youtube-music/assets/49622129/198c5c91-9a5f-45a5-a5a9-d0ce6461e689)

**Comment by JellyBrick** [comment]
https://github.com/th-ch/youtube-music/commit/2f54fa19e6f2758eb291d7abfe044b7759128d3d

Probably because of this commit for fixing UI bugs in YT

This issue can't reproduced in my environment, so I can't think of a way to fix it off the top of my head, sorry. 
(I guess the YT's UI patch was only deployed to some users)

### In my env, Chrome

![image](https://github.com/th-ch/youtube-music/assets/16558115/0644ae58-5262-4923-a015-8cbb1314c623)

### YTMD (3.3.2)

![image](https://github.com/th-ch/youtube-music/assets/16558115/776b15b1-1d91-49db-8265-2672531566f4)

**Comment by makisukurisu** [comment]
Perhaps this update will be of some help.

Videos are shifted down (not centred, as it turns out):
![image](https://github.com/th-ch/youtube-music/assets/49622129/a322cb2d-267e-428e-9957-89782b746329)

[Example song with video](https://music.youtube.com/watch?v=59Q_lhgGANc&si=VwdFtjKc91lW2ydK)

P.S. @JellyBrick, it seems to me that your screen is not big enough to experience the problem. From your screenshot, the app is only 1028px on the Y axis, while the vertical resolution of mine is 1392 px.
And from what I could find with the debugger — code is applied, but, perhaps, the shift is insufficient for my screen resolution.

(Proof of existence)
![image](https://github.com/th-ch/youtube-music/assets/49622129/615e77d3-5227-4d51-9c81-f1537fd8df70)


I'm not that skilled in CSS, or HTML to assist further. But perhaps, a complete overhaul of the UI would be required to fix this with modern approaches of flex boxes or grids. (My futile attempts just broke the UI further 😅). If that's not viable, perhaps there should be another case for some height/width configurations to compensate for the added height.

P.P.S. Sometimes dev-tools gets confused as to the boundaries, so here's a second screenshot:
![image](https://github.com/th-ch/youtube-music/assets/49622129/d78b7624-b359-46ec-a102-34ccb4b59eca)

**Comment by frostybiscuit** [comment]
@JellyBrick I investigated this issue a bit and it is basically caused by two things.

1. The toggle has a padding-bottom, which is not exactly needed if the video is positioned as intended using flexbox or margin auto, depending if it is a video or an image
2. The commit you mentioned adds a negative margin-top to the song-image, hence overwriting the margin-top: auto and making the toggle padding a requirement, but breaking the vertical centering
![image](https://github.com/th-ch/youtube-music/assets/128132341/eeeb9f7a-0e37-4600-b4d8-58e364a88b78)

Since your commit message from the actual line mentions `fix(yt-music bugs): fixed a weird margin-bottom issue when using YouTube Premium` from commit [f8e55f9](https://github.com/th-ch/youtube-music/commit/f8e55f95df875dd7233801f7fe961522b6cde7df), I'm not sure how to recheck that, as I don't have YT premium. The only fix I see is removing that line, but I'm not sure what happens to the YT premium UI as a result.

**Comment by JellyBrick** [comment]
> Since your commit message from the actual line mentions `fix(yt-music bugs): fixed a weird margin-bottom issue when using YouTube Premium` from commit [f8e55f9](https://github.com/th-ch/youtube-music/commit/f8e55f95df875dd7233801f7fe961522b6cde7df), I'm not sure how to recheck that, as I don't have YT premium. The only fix I see is removing that line, but I'm not sure what happens to the YT premium UI as a result.

You can reproduce that issue by enabling `video-toggle > toggle mode > native mode`

**Comment by JellyBrick** [comment]
> Since your commit message from the actual line mentions `fix(yt-music bugs): fixed a weird margin-bottom issue when using YouTube Premium` from commit [f8e55f9](https://github.com/th-ch/youtube-music/commit/f8e55f95df875dd7233801f7fe961522b6cde7df), I'm not sure how to recheck that, as I don't have YT premium. The only fix I see is removing that line, but I'm not sure what happens to the YT premium UI as a result.

@frostybiscuit You can reproduce that issue by enabling `video-toggle > toggle mode > native mode`

**Comment by JellyBrick** [comment]
@frostybiscuit 

### Without f8e55f9

![image](https://github.com/th-ch/youtube-music/assets/16558115/5b46cbbf-cd66-4a15-a48f-61bcb5e9eb50)

### With f8e55f9

![image](https://github.com/th-ch/youtube-music/assets/16558115/0c24fd56-7cd8-47ea-83e8-6b0e121cccd4)

**Comment by frostybiscuit** [comment]
Gotcha!

I've already got an idea. I'll investigate a bit further and try to fix it.

**Comment by makisukurisu** [comment]
Just updated to 3.3.4.0, and on my Windows machine it looks perfect now!
Thanks for your work 🤗 

![image](https://github.com/th-ch/youtube-music/assets/49622129/e764c2bc-a41a-4278-8628-43fbd5d1e5d3)

If you don't mind, I will close the issue, since it was resolved.
