### ISSUE TITLE
Downloading issues

### ISSUE THREAD

**Issue by kirk781** [th-ch/youtube-music#181]
I am using the latest version. When downloading; the download completed, the 'converting' option is displayed and then it fails showing "MIME type error". The audio file is actually downloaded, just without any tag name. I have two questions. I assume this uses youtube-dl for downloading[have it installed]. What does 'conversion' mean? Does it mean converting from .opus to .mp3? I have configured youtube-dl to always output in a certain directory. Is there a way for the app to follow config settings of youtube-dl?

**Comment by th-ch** [comment]
Hey @kirk781, thanks for the feedback! The plugin seems to work ok for me (for the record, it does not use youtube-dl directly but does something similar, downloading then using FFmpeg to convert the file and add metadata) - what are your downloader options? (`Plugins` > `Advanced options`, under the key `plugins` > `downloader`)

**Comment by TotalChris** [comment]
From what I understand this is an issue with ffmpeg. I remember before youtube-dl got taken down there was discussion that ffmpeg wasn't able to convert album art from YouTube Music correctly and apply it to the mp3 file. I don't know what became of that problem but since both youtube-dl and this project's implementation of the downloader are based on ffmpeg, that might be the problem.

**Comment by TotalChris** [comment]
Picture of the error message

![image](https://user-images.githubusercontent.com/41809916/110701049-afe93e00-81be-11eb-839f-63e940498d47.png)

**Comment by kirk781** [comment]
On the latest version of the software, the download seems to work properly with no errors thrown.
