### ISSUE TITLE
Make playlists play all songs

### ISSUE THREAD

**Issue by Enferlain** [th-ch/youtube-music#197]
Is this possible? This is my only issue with any iteration of Youtube Music currently. If I open my big playlist, I would need to start the last song that is shown every time for it to que up more and more of the playlist, which is just not feasible with bigger playlists.

This is mainly an issue for users of shuffle, since if you just go song by song in order you will eventually reach the bottom and it will just continue playing, but if you select shuffle it does not use the pool of the entire playlist, only the songs that are queued up already. 

You can start restart the playlist and select shuffle but since it's random every time, you can get the same songs and need to reset a lot of times to get a unique queue, since if it only queues 50 songs from playlists of 1000 or so, you're working with just a fraction and probably won't get good randomization.

**Comment by Araxeus** [comment]
There are 2 shuffle functions here:
1. Play playlist/big shuffle button actually **load from the whole playlist**, but your queue only **show** the next 50 tracks from the current played
2. The shuffle button in the media control {next to repeat button} will only shuffle the current queue - AKA the next 50 tracks

The easy solution is to use the big shuffle button to reshuffle the whole playlist if needed.
Visually if you want a specific song just select from the playlist, and not from queue

(This is all native Youtube Music Functionality)

**Comment by DereC4** [comment]
THis explains a lot; thank you

**Comment by lehades** [comment]
There's something weird going on with large playlists anyway, but i am not sure it isn't youtube fault as it should be native functionality:

When I play a long playlist in order (clicking on the first song of the playlist, player's shuffle OFF, disabled "auto play" suggestions) and enable "repeat all" the expected behavior would be that the playlist should play all songs and upon finishing the last one it should start again from the first one, but i've found it doesn't do that.

After the last song the player keeps repeating a limited number of songs out of the end of the playlist. My suspicion is that once it reaches the end it starts looping over the 50 last songs of the queue instead of the whole playlist

**Comment by Araxeus** [comment]
^ Native youtube behavior sadly

**Comment by lehades** [comment]
> ^ Native youtube behavior sadly

Yup, native youtube 💩 . I really can't believe they replaced GPM with this half-baked monstrosity.
