### ISSUE TITLE
[Bug]: Ads are not being blocked

### ISSUE THREAD

**Issue by blankets2** [th-ch/youtube-music#2019]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.6.0

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

windows 11 latest as of today's date

### What CPU architecture are you using?

x64

### Reproduction steps

Install app through the windows. easy installation, and or install through Powershell.. Then open the app, click on a song, and watch the ad play. I couldn't get the but to replicate in. the browser link or whatever above this, but I think that's because I have an ad blocker that actually works. And if you're a developer and you say everything is fine cause your app works for you., then keep it to yourself. and don't give it to other people who won't work for. It's just annoying. and that reading the other comments A lot of other people have this problem. and you seem adamant on hushing it up without. doing anything about it. But what does this app anyway? It's just youtube with an ad blocker? Just **** ad block? And the themes are like 6 years old. They're just like Brown and yellow and green. I'm glad this didn't work.

### Expected Behavior

Music to play.

### Actual Behavior

Ads played.

### Enabled plugins

Adblocker both block lists and tried in the music video, whatever the option is Ambient mode. album color. compact sidebar in app menu. navigation picture and picture sponsor block taskbar media control video quality changer which doesn't show up in the video either. No CSS because they all suck and look ugly as ****. Auto updates on I figured that's your app? or is it actual youtube?**** specified in. Jesus Christ. single instance lock, but I just turned that on just for see what would happen. It wasn't on before. I don't think it makes a difference. I did sign in, because I didn't say not to sign in anywhere.. And on Android using another youtube thing. And then affect me at all. Let me sign in with no ads. Disabled system tray. English, restart on config changes. But whatever it doesn't matter like. Get another ad blocker or something or **** **** and get better themes and **** like it ****sucks dude.

**Comment by ArjixWasTaken** [comment]
I had a stroke trying to read that

**Comment by ArjixWasTaken** [comment]
> And if you're a developer and you say everything is fine cause your app works for you., then keep it to yourself. and don't give it to other people who won't work for. It's just annoying

The ads only recently started appearing even for me.

> and after reading the other comments, a lot of people also have this problem. and you seem adamant on hushing it up without doing anything about it.

You made a duplicate issue, if I am to close it I will not be hushing you, since there already exists an issue on the same topic

> But what does this app do anyway? Is it just youtube with an ad blocker?

No, it is youtube music with a lot of plugins that enhance the user experience.

> Just **** ad block? And the themes are like 6 years old. They're just like Brown and yellow and green.

What themes?
Are you talking about the [third-party](https://github.com/kerichdev/themes-for-ytmdesktop-player) themes made by OceanicSquirrel and kerichdev?

> I'm glad this didn't work.

Well, with that attitude, don't expect anyone to waste their time fixing the issues you report.

---

This is not our job, we are not getting paid to work on this, we are not accepting donations to work on this.
We are working on this project because we like working on it.

We have our own lives and jobs outside of this.
The ads have been broken for like 2 weeks max, chill out.

If you are so adamant about fixing this, why not open a pull request?
I was going to fix the ads issue soon, but I am more focused on my plugin [`refined-lyrics`](https://github.com/th-ch/youtube-music/pull/1768) for now.

And you didn't really make me want to change my priorities with your ranting.
