### ISSUE TITLE
[bug] Navigation plugin bug on page load

### ISSUE THREAD

**Issue by Bellisario** [th-ch/youtube-music#202]
For about 1 second with window loading navigation buttons are too big... but, remember that I've tested it with a medium speed connection, so, if you load it with a very slow connection you can also see it for about 5 seconds.

*Here is an attachment of the problem:*
https://user-images.githubusercontent.com/72039923/112209327-9eba1b80-8c19-11eb-984d-a5dacb733be9.mp4

#### Is there any simple way to resolve this problem?
> Yes, you can just make the element with no opacity, then check window load and add the opacity.
> *Optional: add a show transition too, for a more "harmonious" entry!*

**Comment by th-ch** [comment]
Hey @Bellisario, thanks for the feedback! This bug has indeed been here for a long time, it was due to the HTML being injected before CSS had been loaded - fixed it in https://github.com/th-ch/youtube-music/commit/b1665c880b1a18eff7f20c434b148ccfd5001c04 by waiting for CSS to be loaded before injecting HTML elements, it will ship in the next version!

**Comment by Bellisario** [comment]
Thank you @th-ch! I close this issue!
