### ISSUE TITLE
shortcuts plugin blocks native MediaSession api

### ISSUE THREAD

**Issue by Araxeus** [th-ch/youtube-music#204]
see #50
After spending tons of hours researching the [`MediaSession`](https://googlechrome.github.io/samples/media-session/audio.html) API and way of implementation,
I realized Electron supported it all along, it just wasnt working because of the shortcuts plugin

Youtube Music even set it up automatically for each song, no need to do anything,,
⚠️ that includes media key controls, so => 
disabling the shortcuts plugin will still let you use mediakeys control + have native MediaSession support

[This has been tested on Windows && Linux with the help of helpful guys over at Electron]

So anyway I think you probably should atleast remove shortcuts from the **default** plugins, at this state it only *removes* features. - people that want to disable that overlay could just enable the plugin

Example screenshot to show MediaSession api working with youtube-music on windows
![25-03-2021 16 54 07](https://user-images.githubusercontent.com/78568641/112493437-d4324680-8d8a-11eb-8bc7-7adf1885ad1c.png)

**Comment by semvis123** [comment]
Interesting, but after disabling shortcuts the thumbnail/album art still isn't present on macOS, even Spotify has this issue, so my guess is that it is something Apple related. However, the song duration and elapsed seconds are also not present on macOS (the now playing menu), this issue is not present on Spotify and should thus be fixable.

**Comment by Araxeus** [comment]
The duration and elapsed seconds don't show on my pc [Windows] with any app, so I can't really work on that.
maybe you should try :)
[Google example](https://googlechrome.github.io/samples/media-session/audio.html)
[W3 Docs](https://github.com/w3c/mediasession)
[Mozilla Docs](https://developer.mozilla.org/en-US/docs/Web/API/MediaSession)

**Comment by semvis123** [comment]
The duration and elapsed seconds do show on those examples 🤔
So we _could_ try and add those values to the media session, but I don't know if that is going to be easy, I will look into this.

**Comment by semvis123** [comment]
looks like chromium doesn't have the song position implemented, because when I test the example site on Chrome the duration and elapsed seconds are not present, Safari works fine though.
I did however find a npm package that can set the correct song information for macOS (claims that other platforms are supported but it doesn't look like it). Here's a fork of it that also includes the album art.
https://github.com/dimitarnestorov/electron-media-service
That npm package doesn't look like it is being maintained anymore, so I don't know if that is a perfect option.
But maybe this would be a great plugin for macOS only.
