### ISSUE TITLE
Suggesting An End User Persona 

### ISSUE THREAD

**Issue by luluna02** [th-ch/youtube-music#2048]
**The Power of User Personas : Strengthening Youtube Music Desktop App with a User-Focused Approach**

After discussing this with a fellow contributor @KhNediem, we propose incorporating a user persona into the Youtube Music desktop app development. This persona is based on research, surveys, and potential user feedback.

**Why User Personas Matter:** 

The persona will represent the project's target audience's needs and preferences, guiding development decisions.
you can focus on features that align with the user's goals, ensuring the app meets their expectations.
By understanding user pain points, you can create a product that not only meets but exceeds their needs.

We've documented a detailed user persona, including demographics, goals, frustrations, and desired features. We kindly request your review. We believe this addition will significantly enhance our development efforts.

![(Inglés)](https://github.com/th-ch/youtube-music/assets/133816965/be486aea-fea9-42f7-9e8c-477aa870c86e)

**Comment by ArjixWasTaken** [comment]
> The persona will represent the project's target audience's needs and preferences, guiding development decisions.
you can focus on features that align with the user's goals, ensuring the app meets their expectations.
By understanding user pain points, you can create a product that not only meets but exceeds their needs.

And how does that work?
Like really, how can a persona help?

I researched a bit on google, and most of the articles talking about this are for marketing and product design.

Since a persona is fictional, we cannot hold conversations with it.
We cannot hear its opinion on our changes.
We cannot interact with it.

Personas might be just what we need to further improve this project, but we'd also need to know how to use them.

**Comment by ArjixWasTaken** [comment]
(poor Ahmed got his biography stolen by Matt Rodriguez)

**Comment by luluna02** [comment]
> Personas might be just what we need to further improve this project, but we'd also need to know how to use them.
Yes it would be beneficial for future improvements.

**Comment by luluna02** [comment]
> (poor Ahmed got his biography stolen by Matt Rodriguez)



> (poor Ahmed got his biography stolen by Matt Rodriguez)

Omg haha it was a typo :') it's for a a university class anyways so don't mind it too much pls

**Comment by KhNediem** [comment]
[Persona Youtube Music.pdf](https://github.com/th-ch/youtube-music/files/15284365/Persona.Youtube.Music.pdf)

**Comment by ArjixWasTaken** [comment]
> file: [Persona Youtube Music.pdf](https://github.com/th-ch/youtube-music/files/15284365/Persona.Youtube.Music.pdf)
> 
> ## Opportunities
> 1. YouTube Music has an opportunity to regain Wade's trust and loyalty by addressing the shortcomings he has highlighted, such as content availability and user experience.

That feels like it was written by ChatGPT.

Mainly because content availability is mentioned, even though we have no control over youtube's content availability.
That is a mistake an AI would easily make.
