### ISSUE TITLE
[Bug]: Invalid mpris position report

### ISSUE THREAD

**Issue by zoriya** [th-ch/youtube-music#2225]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.12

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Other Linux

### Operating System Version

`Linux fuhen 6.6.36 #1-NixOS SMP PREEMPT_DYNAMIC Thu Jun 27 11:49:15 UTC 2024 x86_64 GNU/Linux`

### What CPU architecture are you using?

x64

### Last Known Working YouTube Music (Application) version

/shrug

### Reproduction steps

1. Enable the MPRIS plugin
2. Start playing a song, wait a few seconds
3. Run `playerctl position` and see something like `0.0025`
4. Seek somewhere on the song (say 1:00`
5. Run `playerctl position` and see the position you seeked to (so 60.567 for example)
6. Wait a few seconds
7. Run `playerctl position` and see the same value (or close to) as before (so 60.4567 instead of 65.12 for example)

### Expected Behavior

Mpris's position should be reported correctly, even when not seeking manually

### Actual Behavior

See reproduction steps.

### Enabled plugins

[YTMusic] Plugin "shortcuts::menu" loaded
[YTMusic] Plugin "lyrics-genius::menu" loaded
[YTMusic] Plugin "downloader::menu" loaded
[YTMusic] Plugin "album-color-theme::menu" loaded
[YTMusic] Plugin "shortcuts::menu" loaded
[YTMusic] Plugin "lyrics-genius::menu" loaded
[YTMusic] Plugin "downloader::menu" loaded
[YTMusic] Plugin "album-color-theme::menu" loaded

**Comment by bqcrabtree** [comment]
I'm seeing this issue still in v3.4.1

**Comment by h-banii** [comment]
I've been having this issue for a while, here's more information about it:

- last known working version: v3.3.6
- I'm almost sure the first bad commit is eaf9d310 
- workaround: reload page through the menu `view > reload`

I could not bisect it properly because there were some broken commits for me, but reverting eaf9d310 seems to fix it.

Here's a demonstration video of the issue (and the workaround):

https://github.com/user-attachments/assets/91b84067-a75d-4369-88cd-5152074ed515

(In the video you can see the position does not update when playing the song, it stays at around the same timestamp)
