### ISSUE TITLE
Electron Builder no longer works

### ISSUE THREAD

**Issue by im-coder-lg** [th-ch/youtube-music#223]
I checked the project 10 minutes ago, and I am new. Electron, for some reason, is not working for the local build installing. I got rimraf but it doesn't work.
This is the same problem with GAUDC, another GitHub project and I can not install it, for some reason.
Check if the local build is working.

**Comment by Araxeus** [comment]
Try running `yarn` / `yarn install` in the project directory, it should fix some problems

(no problem building here)

**Comment by coder-lg** [comment]
doesn't work

**Comment by th-ch** [comment]
Hey @coder-hex, thanks for the feedback! Build looks ok both locally and in CI, have you checked you are using node 12 and tried clearing the yarn cache? (you can find more details in https://github.com/th-ch/youtube-music/issues/246#issuecomment-830776344)

If it sill does not work, feel free to post the commands you run and their output so that we can help you troubleshoot!

**Comment by coder-hex** [comment]
I'll check soon, thanks!

**Comment by coder-lg** [comment]
Ya, node 12.16.2 and npm also is 6.14.4

**Comment by coder-lg** [comment]
Pinging @th-ch
