### ISSUE TITLE
Show this error when starting with tray disabled

### ISSUE THREAD

**Issue by rodrigofanjul** [th-ch/youtube-music#23]
![image](https://user-images.githubusercontent.com/19904663/80624864-ab8eb900-8a22-11ea-95d1-e660b8e5ea07.png)

![image](https://user-images.githubusercontent.com/19904663/80624969-d973fd80-8a22-11ea-8253-f555f5e9138e.png)

**Comment by th-ch** [comment]
Hey @rodrigofanjul, thanks for reporting the issue! This is definitely a bug, introduced by https://github.com/th-ch/youtube-music/commit/058371ace8fbd3d9f126454fdc7dbff86df05506 🤦 
It has been fixed in https://github.com/th-ch/youtube-music/commit/4824dda5d52565deb5cd6ef4b51d2d742677a154 - [v1.3.3](https://github.com/th-ch/youtube-music/releases/tag/v1.3.3) has just been released with the fix, it should solve the issue. I'm closing it but feel free to re-open if it does not work properly!

I'm also looking into adding integration tests to avoid regressions like this one in the future.
