### ISSUE TITLE
[Bug]: (Synced Lyrics): Lyrics stuck at the end when song ends and another one starts

### ISSUE THREAD

**Issue by Dzheremi2** [th-ch/youtube-music#2323]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.5.1

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Other Linux

### Operating System Version

Fedora 40, kernel: 6.9.11-200.fc40.x86_64

### What CPU architecture are you using?

x64

### Reproduction steps

1. Enable Plugin `Synced lyrics`
2. Play a track
3. Open Lyrics tab
4. Wait for track to be ended and next track is playing

### Expected Behavior

Lyrics change and listing from start

### Actual Behavior

Lyrics stuck at the one of ending strings

https://github.com/user-attachments/assets/556c9e79-9b31-419c-b20f-7165816f4b3e

### Enabled plugins

1. Downloader
2. In-App menu
3. Precise volume
4. MPRIS
5. Discord Rich Presence
6. Music Togethed
7. Synced Lyrics

**Comment by ArjixWasTaken** [comment]
does this consistently happen?

**Comment by Dzheremi2** [comment]
> does this consistently happen?

Yes, It is. Every time when music switches automatically. If I switch It manually, everything goes right.

**Comment by ArjixWasTaken** [comment]
I cannot reproduce this on my computer.
This is a wild guess, but it might be a performance issue (?)

What is your power profile on windows?
Is it on performance or power saving?

**Comment by Bugjuice58** [comment]
I think I know where the issue is as I had the same issue. The video element that it uses to track time sometimes (usually when a song naturally ends, and it plays the next one) keeps the currentTime going, without reset. In my fork I fixed this by doing this:
[Creating timeOffset var](https://github.com/Bugjuice58/youtube-music/blob/01fbe9ee277838c2412ea79318221a354ee65a73/src/plugins/synced-lyrics/renderer/index.ts#L17)
[Logic for currentTime - timeOffset](https://github.com/Bugjuice58/youtube-music/blob/01fbe9ee277838c2412ea79318221a354ee65a73/src/plugins/synced-lyrics/renderer/index.ts#L77-L85)
[When new song plays, change currentTime var](https://github.com/Bugjuice58/youtube-music/blob/01fbe9ee277838c2412ea79318221a354ee65a73/src/plugins/synced-lyrics/renderer/index.ts#L90-L94)
I would open a pull request but I'm sure there is a better way to do this.
