### ISSUE TITLE
[Feature Request]: Support for 6K Labs' Amuse Plugin

### ISSUE THREAD

**Issue by AsuToki360** [th-ch/youtube-music#2546]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I usually put some music on my streams, and I really like this app, it's just missing a feature that has the other YT Music Desktop client to make it work with the Amuse plugin which shows the title and artist info, etc.
It's the "Remote Control" option, when that is enabled in the other client it does work with the Amuse plugin, however I would like to hear my music with no ads, and that client doesn't have an ad-blocker.
![image](https://github.com/user-attachments/assets/24cb1c53-ca20-47f8-b57c-487888e03431)
At the moment I'm writing this I haven't even found a similar option in this client, making the Amuse page a bit useless for my streams.

### Proposed Solution

Add a similar option in this client or add a similar option, if possible.

### Alternatives Considered

I'm thinking of something similar could happen if I tried the Tuna OBS plugin, although I haven't tested it yet.

**Comment by ArjixWasTaken** [comment]
I'd assume OBS plugins like that would support mpris metadata (on unix) and whatever alternative windows has.
It is information provided to the OS.

![image](https://github.com/user-attachments/assets/c9e167d0-258c-4cf3-8da7-a3a233e50797)

**Comment by h-banii** [comment]
Apparently, despite Amuse saying they have "youtube music support", they actually mean **ytmdesktop** specifically

amuse: https://docs.6klabs.com/docs/accounts-apps/youtube-music
ytmdesktop API: https://github.com/ytmdesktop/ytmdesktop/wiki/Remote-Control-API

Amuse seems to be closed source and requires login to use, so I couldn't find much

**Comment by ArjixWasTaken** [comment]
They do give an option of connecting specifically to "th-ch/youtube-music", they have a drop-down when customizing the "connection" settings.

The issue is that they are asking for an IP and port, which doesn't make sense, and the guide they have is for ytmdesktop

**Comment by ArjixWasTaken** [comment]
I didn't test if they supported our new http api, but I highly doubt that.

**Comment by ArjixWasTaken** [comment]
As a former maintainer and current contributor, thankfully I can say "fuck it" and not work on this.

If a proprietary service does not give good documentation, and they would make profit from us supporting them...there is no motivation to actually support them.

They could make a PR to fix this, it honestly would be a 30 minute job if given the proper knowledge of how their API works.

(this is my personal opinion and doesn't necessarily reflect the opinion of the maintainers and other contributors)

**Comment by ne0lines** [comment]
Is this happening? I know the Amuse team are interested in supporting this.

**Comment by ArjixWasTaken** [comment]
If anyone with knowledge on undocumented APIs for amuse is willing to make a PR, yes.

Otherwise, no.

Their documentation last time I checked is incomplete.

**Comment by HetIsJoey** [comment]
Id love to implement this in my NowPlaying Widget: https://nowplaying.site/ using the new api-server plugin, although I do have some questions about it.

**Comment by MaxLikesCode** [comment]
@ArjixWasTaken Hey, the developer of 6K Labs here. A forked version of this youtube music application by iryis, who made it to make it work with Amuse, is actually currently in use. I tried the new api server, but there are some issues I encountered. I'd like to talk to you about it as well as giving you the documentation you were looking for.

**Comment by ArjixWasTaken** [comment]
I'm all aboard then!

I'd prefer if you could share this information in this issue, so that other contributors can view it as well.

**Comment by MaxLikesCode** [comment]
> I'm all aboard then!
> 
> PS: I'd prefer if you could share this information in this issue, so that other contributors can view it as well.

Sounds great! First of all, thank you for maintaining and contributing to this app. I really like it myself and it offers a very smooth experience.

I was about to report an issue regarding the elapsed seconds not updating when querying `/song-info`, but after some digging, I found out that @Azorant had actually [created a fix for it](https://github.com/th-ch/youtube-music/pull/2558) based on [this issue](https://github.com/th-ch/youtube-music/issues/2518), which described my problem exactly. I was wondering why I was still experiencing the issue but then realized that the fix was made on October 28, roughly two weeks after the most recent release, v3.6.2, on October 16. It seems all that’s needed for it to work is a new build, assuming the pull request did indeed fix it. When do you think a new release will be possible? If there’s anything I can do to help, please let me know.

Additionally, since Amuse is so popular and people love this YouTube Music desktop app, especially because it has an ad blocker, I think it would make sense to have a dedicated plugin for Amuse. Since the api server can change over time, I’d like to have the peace of mind that the plugin remains stable and stays in sync with Amuse's development. Maybe we can get @iryis in the boat to port their implementation with some changes into the main branch since theirs worked great so far. If I remember correctly, iryis was waiting for the [api server to be merged](https://github.com/th-ch/youtube-music/pull/1909) so they could [port their implementation](https://github.com/th-ch/youtube-music/pull/1909#issuecomment-2349201777) into the main branch, making use of the api server.

While the documentation isn’t too strict yet and instead adapts to whatever the app offers, having some standards would be beneficial. A few potential rules could be: 
1. The app should be able to be called from a port on `localhost`. 
2. The endpoint should be able to handle 60 requests per minute. 

I've seen some apps put rate limiters on localhost queries. While I appreciate their security measures, I think this is a bit much.

Another standard could be ensuring that the endpoint returns at least the following values: 
- `title`
- `artist`
- `duration`
- `elapsedSeconds`
- `isPlaying`
- `coverUrl`

I'm not sure if `isAdvertisement` can be implemented or if YouTube doesn’t expose that information or if it’s just too difficult to scrape it efficiently. That said, as far as I can tell, the api server already meets all these requirements.

**Comment by iryis** [comment]
> Apparently, despite Amuse saying they have "youtube music support", they actually mean **ytmdesktop** specifically
> 
> amuse: https://docs.6klabs.com/docs/accounts-apps/youtube-music ytmdesktop API: https://github.com/ytmdesktop/ytmdesktop/wiki/Remote-Control-API
> 
> Amuse seems to be closed source and requires login to use, so I couldn't find much

Amuse backend currently conforms to their project's no longer used APIs for Youtube Music support. My fork is simply a mapping of SongInfo to ytmdesktop data structure.
I can port this 1 to 1 if that is okay, otherwise it would require a few changes on @MaxLikesCode's end as they are similar but not the same; plus it wouldn't be backwards compatible with however-many users are currently using that fork.

**Comment by ArjixWasTaken** [comment]
@iryis a 1:1 porting should be fine, as long as the code is not total spaghetti 🤣 
if you need help reviewing the code, etc feel free to tag me in your PR

**Comment by lucas-mayca** [comment]
Hello, I'm not sure if this is the right place for this comment. I'm a complete novice and don't understand anything about programming. I installed the Amuse widget in Obs Studio, and it appears on the screen fine, but it's not counting the music time; it stays at zero. And the loading bar doesn't even track the music progress. Is there a setting I need to change to fix this?

**Comment by lucas-mayca** [comment]
I managed to fix the problem by enabling the media control option on the taskbar, sorry if I posted this information in the wrong tab
