### ISSUE TITLE
[Feature Request]: Try to add the connect to a device feature from spotify 

### ISSUE THREAD

**Issue by Zippu-4249** [th-ch/youtube-music#2619]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

.

### Proposed Solution

Try to add the connect to a device feature from spotify . I think most of the users would like it , so we can switch/transfer the media  between multiple desktops , laptops and speakers . I myself have 2 laptops and 2 speakers but i have to connect and disconnect the bluetooth and its a hassle to be honest .
![image](https://github.com/user-attachments/assets/72453be6-5dda-43dc-b2c9-933d58cfd1b4)

### Alternatives Considered

.

**Comment by ArjixWasTaken** [comment]
For this to be possible, a bunch of things will need to be done.
Specifically:

1. Having our own backend where you would login, in order to have the concept of "session".
2. Having a revanced plugin for the mobile app, to introduce the required functionality.

There may be more requirements, but with just these two alone I can say that this is a hard request.
It would be an awesome feature for sure, but kinda unrealistic with the way things are.

youtube music does not share the "session" concept of Spotify, you can be listening to multiple songs from multiple devices/browsers using the same account at the same time

**Comment by Zippu-4249** [comment]
I see ..... thanks for the information

**Comment by JellyBrick** [comment]
You can use `Music Together` plugin
