### ISSUE TITLE
[Feature Request] ListenBrainz support

### ISSUE THREAD

**Issue by LolzNeuer** [th-ch/youtube-music#276]

**Comment by semvis123** [comment]
The data can be imported from last.fm to ListenBrainz, so I don't know if it's necessary to add specific support / create a new plugin. Would like to hear your opinion about this.

**Comment by LolzNeuer** [comment]
Well I feel like it would be nice to have a plugin that could support multiple websites similar to how Web Scrobbler works.

**Comment by nethershaw** [comment]
Almost all third-party scrobblers (those not published by last.fm) are capable of publishing listens to multiple scrobbling APIs (last.fm, listenbrainz, gnu fm/libre.fm/hacienda) because under the hood they are all just JSON objects.

I can do _almost_ all the things in this implementation of YouTube Music; but because it has no access to my browser extensions, e.g. Web Scrobbler has no access to what it's doing either even though it's nominally just another thin Web client.

Because of the (severe, clumsy, manual) limitations of importing listens from one service to another, especially in this particular direction, it is never preferable to simultaneously scrobbling to multiple targets. You might want to be present in more than one community at the same time.

Considering this is a solved problem elsewhere, it represents a feature deficit here.

**Comment by JellyBrick** [comment]
Tracked on #1350
