### ISSUE TITLE
[Bug]: i cannot download music

### ISSUE THREAD

**Issue by gokulcoder7** [th-ch/youtube-music#2769]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [ ] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.7.0

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Home

### What CPU architecture are you using?

x64

### Reproduction steps

select any music and click download

### Expected Behavior

i want to download songs(.mp3)

### Actual Behavior

![image](https://github.com/user-attachments/assets/826876b9-f249-4567-9081-4cf01d630135)

### Enabled plugins

![image](https://github.com/user-attachments/assets/4ef7a35a-05cf-44fb-a383-bba4a5f5b029)
add blocker is also enabled

### Additional Information

![image](https://github.com/user-attachments/assets/826876b9-f249-4567-9081-4cf01d630135)

**Comment by MoElshahawy** [comment]
F
Same problem

**Comment by errorb0t** [comment]
Same, notably after updating to 3.7.0

**Comment by JellyBrick** [comment]
Can you provide the URL of the track?

**Comment by sxoni** [comment]
> Can you provide the URL of the track?

in any track this happens, like this:

https://music.youtube.com/watch?v=I7A1Qvgl9MI&list=RDAMVMI7A1Qvgl9MI

![image](https://github.com/user-attachments/assets/4adbd34c-b8c0-40a4-ae8e-f6a9d53c654d)

**Comment by ImaDoor2785** [comment]
same here

**Comment by errorb0t** [comment]
> Can you provide the URL of the track?

It's every instance of the download button I've tried. I only installed the app yesterday, and I've been getting three (since 3.7.0, two) types of errors. "This playlist is empty", when trying to download albums saved from library, and the error mentioned in this thread for anything else. Example links that I'm getting the error on (generated using the 'share' button):
https://music.youtube.com/watch?v=nlcIKh6sBtc&si=h7xgU8Nro1RMwneP
https://music.youtube.com/watch?v=B-XivnZunVM&si=fK4lEThc0eraFHtI
https://music.youtube.com/watch?v=g7W7MisCKWk&si=5ksBtq77I4OYy_VC
Also playlist links, although the playlist folder gets created and the error pops up for every song in the playlist:
https://music.youtube.com/playlist?list=PL53mjgVKFq7yu0LdAvpp42ZGLzRCkFKuz&si=nDxnwM5L19Lmk8O9.

Only changed setting on my part from default is enabling the download plugin.

**Comment by JeffKeane** [comment]
same, pls fix :(

**Comment by Volcaholic8** [comment]
identical error message as already described by others. since 3.7.0 - portable Version 
Windows 10 Pro

Song example: https://music.youtube.com/watch?v=bzLlCQQegL0
But I tried it with many songs and always got the error message. I tried changing the download folder, tried using VPN. Always the error message.

**Comment by OGxBEAST** [comment]
Same issue 🥲

**Comment by MaxterXen** [comment]
This has been a problem for me for a while, hoped the update would fix it but it didn't. I guess we have to wait now. I guess no Ultrakill music on my HP iPAQ for now.

**Comment by errorb0t** [comment]
Perhaps interesting for troubleshooting: Short songs - and only short songs - still work for me, the songs linked are 0:32 and 0:37 respectively. I've tried other songs shortly before and after to rule out other circumstances changing.
https://music.youtube.com/watch?v=1_vkmjnOlwQ&si=hzmiCrPu5VHQWKz6
https://music.youtube.com/watch?v=B5leUzYa_qo&si=SKaLBmb1YcbZesHq

**Comment by Mad880** [comment]
Hey, I still get this error even after updating to 3.7.1

**Comment by arzezio7** [comment]
Download issue still persists in latest build (3.7.1.0 . Now with same error of variant status codes when try to download

![image](https://github.com/user-attachments/assets/b8a8c1cf-08fe-48b2-98fc-e31fede4ec8a)
![image](https://github.com/user-attachments/assets/b0e809c7-c398-48fc-bf69-26fbef51ab5e)
