### ISSUE TITLE
[BUG] Illegal access, app freezes.

### ISSUE THREAD

**Issue by semvis123** [th-ch/youtube-music#291]
This can happen when the app launches (around 1 second after the song starts playing), I don't know what causes it.
Only seems to happen when a plugin is active that uses the song info provider.
I'm using the latest master branch.
This happens on both macOS and Windows.  

<img width="570" alt="image" src="https://user-images.githubusercontent.com/28219076/118645244-f7073700-b7de-11eb-96fd-f07b44fb19d4.png">
<img width="570" alt="image" src="https://user-images.githubusercontent.com/28219076/118627240-d71a4800-b7cb-11eb-97a5-308ed8f2862d.png">
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/28219076/118645703-8ca2c680-b7df-11eb-8e7b-fc238dc77d40.png">

**Comment by semvis123** [comment]
Looks like this issue doesn't occur in https://github.com/th-ch/youtube-music/pull/269 , so I assume that issue was because of the duplicated callbacks.

**Comment by Araxeus** [comment]
I have encountered this too. 
did it happen for you in dev mode or in already compiled app? (it seems to happen only in dev mode to me)

I'm not sure #269 fixes this, this error is pretty rare so its hard to be sure

I also think it might be a problem with electron, hopefully the one that was fixed in https://github.com/electron/electron/pull/29093 (4 days ago, unreleased yet)

**Comment by semvis123** [comment]
It did happen both in build and in dev mode. On the master branch it's about 1/10 times, and I haven't seen it in the #269 version yet, so it is definitely more rare there, not sure why.
Hope it is fully fixed in https://github.com/electron/electron/pull/29093.
