### ISSUE TITLE
2 Factor Authentication on Google Account reports wrong device type on "New sign-in alerts" and Google Account security activity.

### ISSUE THREAD

**Issue by ESodikromo** [th-ch/youtube-music#327]
When logging in to the app, using 2FA will send a message to another device to confirm the login request. However, instead of displaying the correct info for the machine used to login (Windows, Laptop Name), all that was reported was a nondescript "Mac" machine. The reported location was correct, however. This same info is accessible from the Google Account/Security If this is intended, explain so on the download page or in the app to prevent confusion and worry over unspecified login attempts.

**Comment by Bellisario** [comment]
Yes, in fact to prevent Google from blocking the login, there is Mac user agent, but the problem is that isn't explained correctly...
Here are two solutions:
- Advert the user the login is "made" by a Mac (a false Mac);
- Detect platform and send to Google Login an user agent that respects the platform detected (ex. Windows as Windows, etc. and not Windows as Mac)

**Comment by Araxeus** [comment]
This issue should be fixed and can be closed
