### ISSUE TITLE
YT Music showing Blue box on Icons (BUG)

### ISSUE THREAD

**Issue by Rarab5534** [th-ch/youtube-music#336]
Hello Its Rarab

I have been using Youtube Music since the past few days now and recently i cant like a song and click on anything that is releated to the music like downloading for example.

So can you please fix this with the new update 

Thanks 
Rarab

**Comment by Goldenfreddy0703** [comment]
Yeah i've been experiencing the same thing. It started happening today when i was working on some new software.

**Comment by Rarab5534** [comment]
> 
> 
> Yeah i've been experiencing the same thing. It started happening today when i was working on some new software.

Well just use the https://music.youtube.com/ and use ublock orgin has the adblocker

**Comment by Rarab5534** [comment]
uwu
![Acorn](https://user-images.githubusercontent.com/86423147/123481786-1c683b80-d5fc-11eb-9d61-efaeb752c569.png)

**Comment by th-ch** [comment]
Hey @Rarab5534, thanks for the feedback! The issue is confirmed but seems to come from YouTube Music itself when loading a video page directly (the same happens in the browser `Uncaught TypeError: this.playerApi.setMinimized is not a function`) - a workaround for now is to disable `Options > Resume last song when app starts` to start on the homepage, this way the error does not happen.
