### ISSUE TITLE
adblocker not working

### ISSUE THREAD

**Issue by Sart-Hack** [th-ch/youtube-music#360]
i just recieved an ad on the app for the first time. The ad blocker plugin is on.

**Comment by th-ch** [comment]
Hey @Sart-Hack, thanks for the feedback! A [new version](https://github.com/th-ch/youtube-music/releases/tag/v1.12.2) has been released and updates the plugin, can you give it a try to see if it solves your issue?

**Comment by JamieChamberlain** [comment]
Sometimes this has been happening to me but you can fix this if you click on plugins and click on adblocker and re-enable by clicking on it again and restart the app 

Hope this helps,
Jamie Chamberlain

**Comment by AuracleTech** [comment]
![image](https://user-images.githubusercontent.com/40531871/141207392-e92e4504-c780-4183-a84a-6cb7d6d6846d.png)
BRUH

**Comment by typinghands** [comment]
I can confirm that the adblock keeps working inconsistently, unfortunately. At least for non-US based countries (I am in Europe) most of the times the first song after opening the program will contain an ad. 
I have tried turning on/off the adblocker and restarting the app (as some people suggested), but it didn't solve the issue (I'm on the latest version of the app).

Because this happens in the first 1-2 minutes of the app being first opened (and never afterwards for me, as long as the app stays open), I suspect it has something to do with the speed or order in which the adblocker component gets loaded? This issue is particularly problematic with an option like 'resume last song when app starts' active.

**Comment by Araxeus** [comment]
I have an experimental faster adblocker here: https://github.com/Araxeus/youtube-music/tree/experimental-faster-adblocker

Looking for people to test it (I don't get any ads with it enabled, but that might be just luck since they are pretty rare for me)

**Comment by Araxeus** [comment]
Can anyone give feedback on the Pull Request? it has downloadable binaries if needed
