### ISSUE TITLE
Not downloading a playlist

### ISSUE THREAD

**Issue by vihaan1234567** [th-ch/youtube-music#516]
It's not downloading a playlist. Just loading continuously.
What do I do to solve this?

**Comment by XclusivVv** [comment]
I am having the same issue. When trying to download a public playlist, it fails without giving any messages. Checking the dev tools logs shows the following:

`electron/js2c/renderer_init.js:13 (electron) The remote module is deprecated. Use https://github.com/electron/remote instead.
log @ electron/js2c/renderer_init.js:13
music_polymer_inlined_html.js:3345 LegacyDataMixin will be applied to all legacy elements.
Set `_legacyUndefinedCheck: true` on element class to enable.
2music_polymer_inlined_html.js:1637 observer method `showSeekButtons_` not defined
ps @ music_polymer_inlined_html.js:1637
Error with Permissions-Policy header: Unrecognized feature: 'ch-ua-bitness'.
electron/js2c/renderer_init.js:13 (electron) The remote module is deprecated. Use https://github.com/electron/remote instead.
log @ electron/js2c/renderer_init.js:13
C:\Users\X\AppData\Local\Programs\youtube-music\resources\app.asar\node_modules\ytdl-core\lib\utils.js:175 WARNING: ytdl-core is out of date! Update with "npm install ytdl-core@latest".
(anonymous) @ C:\Users\X\AppData\Local\Programs\youtube-music\resources\app.asar\node_modules\ytdl-core\lib\utils.js:175
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/ajv.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/context.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/boolSchema.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/uri.all.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/util.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/iterate.js.map: Unexpected token < in JSON at position 0
2DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/index.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/scope.js.map: Unexpected token < in JSON at position 0
2DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/code.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/applicability.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/error_classes.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/index.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/core.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/errors.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/subschema.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/defaults.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/keyword.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/multipleOf.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/pattern.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/ref.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/enum.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/rules.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/required.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/items.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/limitLength.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/limitProperties.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/contains.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/ucs2length.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/limitNumber.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/const.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/uniqueItems.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/limitItems.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/id.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not load content for https://music.youtube.com/s/7dfebb19/blaze-out/k8-opt/bin/third_party/javascript/polymer/v2/webcomponentsjs/webcomponents-sd.js.sourcemap: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://music.youtube.com/s/7dfebb19/web-animations-next-lite.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://music.youtube.com/s/7dfebb19/blaze-out/k8-opt/bin/third_party/javascript/custom_elements/fast-shim.js.sourcemap: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/additionalProperties.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/dependencies.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/propertyNames.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/not.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/additionalItems.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/properties.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/oneOf.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/allOf.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/thenElse.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/if.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/anyOf.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/format.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/index.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/preload.cjs.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/index.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/dash-mpd-parser.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/m3u8-parser.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/parse-time.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/menubar.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/arrays.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/menu.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/keyCodes.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/keyboardEvent.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/browser.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/color.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/menuitem.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/mouseEvent.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/iframe.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/platform.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/async.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/themebar.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/event.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/iterator.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/titlebar.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/queue.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/lifecycle.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/dom.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/event.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/linkedList.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/index.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/draft7.js.map: Unexpected token < in JSON at position 0
3DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/index.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/names.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/metadata.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/index.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/dataType.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/resolve.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/patternProperties.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/browse/ffmpeg.min.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/ytmusic-base-styles.css.map: Unexpected token < in JSON at position 0`

Is this happening because ytdl-core wants to be updated?

**Comment by vihaan1234567** [comment]
Still hasn't been rectified..

**Comment by th-ch** [comment]
Hey @XclusivVv and @vihaan1234567 it seems to work fine for me, have you tried with the [latest version 1.15.0 (in prerelease)](https://github.com/th-ch/youtube-music/releases/tag/v1.15.0)?

**Comment by XclusivVv** [comment]
Hello @th-ch still the same problem persists with the pre-release version.

Playlist is public. Audio tracks play from the playlist. Problem only occurs when trying to download playlist. I recorded a video showing the tracks play.

DEVTOOLS LOG: https://pastebin.com/0xbgLB57
VIDEO RECORD: https://streamable.com/l2anpn

Is there any other information you need from me to figure out why this is happening?

**Comment by Araxeus** [comment]
> Playlists download without any issues when selecting "Plugins > downloader > download playlist" from the toolbar.

Thats actually the only way to download a playlist currently

The menu that is shown in your recorded video is the same menu that is shown for normal songs
So when you click 'download' there, it tries to download a song and not a playlist

Anyways the real bug here is that you can see the 'download' button in the context menu even tho it should only show on songs

**Comment by Araxeus** [comment]
I've opened a PR (#549) which will allow downloading playlists straight from the popup menu (like in the video that was sent)
