### ISSUE TITLE
Hotkeys

### ISSUE THREAD

**Issue by thijsi123** [th-ch/youtube-music#52]
The hotkeys are not always working and while pressing the pause hotkey the song pauses and after 1 second starts on it's own.

**Comment by th-ch** [comment]
Hey @thijsi123, thanks for the issue! Do you have the `auto-confirm-when-paused`plugin enabled? We have a [known bug](https://github.com/th-ch/youtube-music/issues/18#issuecomment-619732798) with it, it currently does not play well with the media keys (mainly because play/pause is achieved by emulating a space keypress). I might have a fix for this, keeping this issue open to track progress.

**Comment by thijsi123** [comment]
Thanks it is enabled. I will keep it in mind.

**Comment by venomin** [comment]
I have issues with hotkeys too.
If I had used the media button on some other media (i.e. youtube in my browser), the hotkeys stop working for the app. they will continue to contol different media, even if I switched to the app. With other apps and media there's no such issue
