### ISSUE TITLE
Scrobbling Issues

### ISSUE THREAD

**Issue by trevorraney** [th-ch/youtube-music#540]
Using version 1.15.0. When playing an album, only the first track will be properly scrobbled to Last.fm. Subsequent tracks will appear in Last.fm as "scrobbling now" but then not commit.

![image](https://user-images.githubusercontent.com/64988493/148085545-1d6ef429-59c9-409e-a67a-58fabd511213.png)
![image](https://user-images.githubusercontent.com/64988493/148085562-915928d2-ddbd-4fb9-9f7c-a6ff81554466.png)

**Comment by Araxeus** [comment]
@semvis123

**Comment by trevorraney** [comment]
Do you just mean the console accessible through `Shift+Control+I`? Want to make sure I'm looking in the right place.

**Comment by Araxeus** [comment]
@semvis123 does it works for you on v1.15?

something might have broke in the last updates (song-info was changed slightly tho I can't see how it would break things)

if it doesn't work for you either then *maybe* #537 could be a possible fix

**Comment by trevorraney** [comment]
Lot of warnings that start with "DevTools failed to load source map: Could not parse content for..." No errors. 
![image](https://user-images.githubusercontent.com/64988493/148100078-3e7c7db5-829a-464c-83a8-df8fdeb8a034.png)

**Comment by semvis123** [comment]
Can't reproduce the issue (everything gets logged correctly), i'm using 1.15 with no extra plugins enabled (except the plugins enabled by default)

(btw did not notice that this project had improved so much since I last checked, well done :) )

**Comment by trevorraney** [comment]
Commenting just to say the problem still persists when playing an album in version 1.16.0. But when you play a song and autoplay is enabled, songs are scrobbled correctly.

Songs — played from an album or otherwise — appear correctly in Discord though.

**Comment by bytang** [comment]
I've been experiencing this since 1.14 until now on 1.16 still the same issue. Since the plugin author doesn't experience this, I tried a clean reinstall of the app and found scrobbling working as intended. Then, I signed in to my Google account and scrobbling broke. Then I signed out and scrobbling works again.

**Comment by trevorraney** [comment]
Not sure if it would be of any benefit to check them out, but I've been trying out [Cider's Apple Music app](https://github.com/ciderapp/Cider), also based on Electron. Their implementation of Last.fm scrobbling and Discord rich presence has worked great for me so far.

**Comment by tariqchhussain** [comment]
Giving this issue a bump as I have been coming across an issue, which is not exactly the same as OP's, is still fairly annoying. I'm not sure if I'm the only one experiencing this, but when I scrobble a track, all metadata except for the album is scrobbled which leaves gaps in my last.fm history. On the contrary, there are Chrome extensions that scrobble the album metadata, and I was wondering why this isn't the case for this application? Not entirely the end of the world, of course, but its the only obstacle stopping me from using this application full time. Don't get me wrong, this application is near perfect but I would still love for this issue to be looked at and fixed if possible.

(I'm currently on 1.16.)

**Comment by Araxeus** [comment]
Album name is not available when the current song is a video, but it could still be sent when it is a normal song

should be easy to fix:
https://github.com/th-ch/youtube-music/blob/23058729f3965deb0bff9b638feb5d419da6e913/plugins/last-fm/back.js#L88-L96
add
```js
{
album: songInfo.album
}
``` 
(will be undefined when not available)

also should probably add a timestamp value there since it seems to be required? 
https://www.last.fm/api/show/track.scrobble

**Comment by tariqchhussain** [comment]
Hey, thanks for replying so swiftly! I've just tested the changes to the backend, and it appears that it works... kind of. It is indeed sending something to last.fm, but according to what I've seen in Pano Scrobbler, the album title is coming up as "undefined" instead of the actual title. I've tried with many songs (not videos) and it seems to be reproducing the same results. Any ideas?

**Comment by Araxeus** [comment]
use `...(songInfo.album ? { album: songInfo.album } : undefined)`

**Comment by renatolond** [comment]
Hey, I'm having the issue here. I tried keeping the network tab issue but I'm not even seeing scrobbling requests there (even though I also see the tracks as "scrobbling now" but they never seem to be commited).
I also tried upgrading to 1.17 to get the changes in #695 but it doesn't seem to make a difference.
