### ISSUE TITLE
Last.fm "Waiting to scrobble"

### ISSUE THREAD

**Issue by pratyakshm** [th-ch/youtube-music#546]
Hi,
I have enabled the last.fm plugin and given Last.fm access to YouTube Music desktop app, but it still doesn't scrobble and instead shows "Waiting to scrobble". Is there anything that I haven't done right?

Console output if necessary:
<details><summary>Tap to toggle picture visibility</summary>

![image](https://user-images.githubusercontent.com/54220235/148733159-0a26751e-7cad-4dd2-b425-bd3d7ee846b1.png)
</details>

**Comment by semvis123** [comment]
Scrobbles only get added once you listen +50% of the song, or pass the 4 minute mark. So if you skip the song before that it won't be added. Might need a restart of the app to fully work btw

**Comment by pratyakshm** [comment]
I listened to the full song, but Last.fm still did not scrobble.
I also re-installed both apps but it didn't help.

**Comment by pratyakshm** [comment]
Closing as ignored.

**Comment by Zo-Bro-23** [comment]
> Closing as ignored.

Don't close because an issue was ignored. It might still affect other users, so keeping it open will avoid duplicates. Someone else might find a fix too, but closing it will prevent it from being visible when searching for issues on the repo homepage. (I've received fixes for issues I created after some 2 years, so there's still hope 🙃)

**Comment by Zo-Bro-23** [comment]
Also, Last.fm tends to have bugs with integrations. The Spotify official integration doesn't work sometimes either. Try reconnecting the integration by logging out from YTM and disconnecting from Last.fm integration page. Then try connecting again.
