### ISSUE TITLE
plugin conflicting "Video Playback"

### ISSUE THREAD

**Issue by thijsi123** [th-ch/youtube-music#560]
Hey, sorry for last time (forgot to close the issue😅)

I found out that the "Video playback" plugin conflicts with "restart on config changes"

Switching between video and song works normal but when I select next song/video the app restarts with different playlist.
Everything works great when I turn off "restart on config changes"

I added a gif with that shows the program restarting. (the pink is just a background nothing to do with yt music : ) )

I tried looking into it myself but I can't seem to fully understand how everything works since the only langue I can understand a bit is lua (zero to nothing of scripting experience) and don't know where the location of "restart on config changes" is.

![ezgif com-gif-maker (5)](https://user-images.githubusercontent.com/64159148/150391801-d61ec801-e45a-4c3a-b6b5-43f171cfdec2.gif)

**Comment by Araxeus** [comment]
Well it makes sense because the config is changing in real time without you doing anything (its not the only plugin that saves data to config) 

and then the app restarts because it was changed...

https://github.com/th-ch/youtube-music/blob/2ad6c0fcdc16a398b9020d23eb0f542be4452a8c/index.js#L310-L315

@th-ch what do you think? should the restart on config change option be removed?

**Comment by Araxeus** [comment]
I have created a PR that will fix this (#561)

Thank you for reporting this!

**Comment by thijsi123** [comment]
> I have created a PR that will fix this (#561)
> 
> Thank you for reporting this!

It's nothing : )
