### ISSUE TITLE
Add support for media keys using mpris2 on the linux platform

### ISSUE THREAD

**Issue by jrabinow** [th-ch/youtube-music#65]
This app is perfect in every way ❤️ , except for one thing: currently, media keys don't seem to work on my setup (linux).

Would it be possible to add support for the mpris2 protocol? You can find a working implementation [here](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/src/main/features/linux/mprisService.js)
and the full spec is [here](https://mpris2.readthedocs.io/en/latest/) in case you needed to refer to it

**Comment by azizLIGHT** [comment]
There is some kind of mpris implementation because it works for me on Manjaro on Gnome. I can press pause/play/prev/next successfully. Maybe its not to spec like you say as some things are working for some and not others? In any case, here's what I noticed related to mpris:

When i query qdbus for track information by mpris, the app name is a random chromium instance number like `org.mpris.MediaPlayer2.chromium.instance1820402` instead of something like `org.mpris.MediaPlayer2.youtube-music`. I also can't query full track information with `qdbus org.mpris.MediaPlayer2.chromium.instance1820402 org.freedesktop.DBus.Properties.Get org.mpris.MediaPlayer2.Player Metadata` like you would for a player like vlc, I get nothing returned back on the prompt. [A Gnome extension](https://github.com/JasonLG1979/gnome-shell-extension-mpris-indicator-button/) I use to display now-playing information in my top panel can find track information, but the Artist always has `- Topic` appended at the end of it for whatever reason. The notifications show proper track information however. 
Hope this info helps implementing the mpris spec fully!

**Comment by jrabinow** [comment]
@azizLIGHT I can only guess why it's working for you but not for me: since you mention you're using Gnome, would it be possible for Gnome to be using its own media keys solution independent of mpris? Maybe even something similar to [this](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/src/main/features/linux/mediaKeysDBus.js)

On my end, my DE has no such media key service built in. I'm using a keyboard shortcut tied to https://github.com/mackstann/mpris-remote (actually I updated the code [a fair bit](https://github.com/jrabinow/homedir-scripts/blob/master/mpris-remote), long story short it works with mpris2. Tested and confirmed all players work except this one). The way it works is it scans dbus for any mpris-compatible players and issues them the command - so my guess is the name of the app doesn't matter, it's just that there's no mpris support at the moment

**Comment by th-ch** [comment]
Hey @jrabinow & @azizLIGHT, thanks for the precise feedback! I have opened a draft PR https://github.com/th-ch/youtube-music/pull/78 but I have no setup to test it 😬 
Feel free to test it out and update the issue accordingly! To run it, you need node.js and yarn, then:
```sh
git clone https://github.com/th-ch/youtube-music
cd youtube-music
git checkout mpris
yarn
yarn start
```

**Comment by jrabinow** [comment]
Hey @th-ch thanks so much! I'm afraid there's a bug somewhere, attached are the tracebacks:

[dbus-monitor-out.txt](https://github.com/th-ch/youtube-music/files/5632771/dbus-monitor-out.txt)
[mpris-remote-cmd-out.txt](https://github.com/th-ch/youtube-music/files/5632773/mpris-remote-cmd-out.txt)

I'm not sure if you have a linux distro available to test things out on, if you do you can check out [playerctl](https://github.com/altdesktop/playerctl) or [mpris-remote](https://github.com/jrabinow/homedir-scripts/blob/master/mpris-remote)... otherwise I'll do my best to test things out whenever I get the chance

**Comment by JoeJoeTV** [comment]
Are there any updates to this? I could maybe test it on my Linux Mint install, if that helps.

**Comment by itzmanish** [comment]
I have tested on Arch linux with playerctl. So please merge this.

**Comment by itzmanish** [comment]
@th-ch when this will be release? I am waiting only for this because I don't know how do I install in arch linux. (PS- I am also lazy to go through tutorials)

**Comment by th-ch** [comment]
Hey @itzmanish, I still need to go through a few PRs (like https://github.com/th-ch/youtube-music/pull/389) and then I'll release a new version, probably in the following weeks!

**Comment by jrabinow** [comment]
I'm going to close this issue as all changes have shipped with the latest release. If people are still running into problems, please feel free to reopen.

Thanks everyone!

**Comment by JoeJoeTV** [comment]
I'm still having issues with this after updating to the newest version(1.14.0).
The mpris2 control now properly shows YouTube Music with the song info(title and artist) and also the cover, but only the previous and next buttons work.
There is also still a "Chromium" control, that shows the song info without a cover art, but there, all buttons(previous, play/pause, stop and skip) work in contrast to the "correct" control.

I'm on Linux Mint Cinnamon 20.2 64x and have installed the .deb version.

**Comment by Araxeus** [comment]
@JoeJoeTV I have possible fixes in mind but no way to test on windows. would you be willing to help me test?

if so add me on discord `Araxeus#0819`
