### ISSUE TITLE
Youtube Music interface do not remember on which monitor it was last opened.

### ISSUE THREAD

**Issue by ZeroCool940711** [th-ch/youtube-music#652]
Hi there, I'm having a small issue with the Youtube Music interface where for some reason it will always open on the main monitor instead of the last used monitor, in my case I have 4 monitors and I keep Youtube Music always open on my 3rd monitor, after having it open for a while I have to restart Youtube Music as the UI becomes a bit unresponsive every now and then, when I restart the app it will always open the interface at launch on the main monitor, in other words in monitor 1, after that I have to move the interface to the 3rd monitor where I usually have it. While this is not a big deal it is a bit annoying sometimes and it was not happening before on older versions.

**Comment by Zo-Bro-23** [comment]
In Windows, the keyboard shortcuts "Win + Shift + Arrow" does not remember the last used monitor for some reason. If I use the shortcut to shift an application to a different monitor, the next time it opens on my primary monitor, regardless of the application. Try windowing the application (instead of full screen), and dragging it to a different monitor. Then maximize the application and let me know if you have any issues. If you're not on Windows, then I don't know the solution, sorry 😔

**Comment by ZeroCool940711** [comment]
@Zo-Bro-23 Interesting, I always use the shortcut "Win + Shift + Arrow" to move the window from one monitor to another so that explains why it always goes back to the main monitor after a restart, after trying moving it by dragging the window around as you said and then maximizing it, it does remember the last used monitor. Really appreciate the help, hope this issue helps other people with the same issue. :)
