### ISSUE TITLE
UP NEXT doesn't reposition properly on next song

### ISSUE THREAD

**Issue by OnTheRocksBrew** [th-ch/youtube-music#688]
I'm not sure if this is native to the app or something to do with this project but if the last played song is the last visible one in the _UP NEXT_ menu then when the next song is loaded up, it is not visible in the _UP NEXT_ menu. I can reproduce this every time by scrolling so that the current song isn't visible, and then hitting the next button (interestingly the previous button doesn't have this same issue). This behavior makes me confused as to where I am in the list, every time :)

I would think the loaded song should either be at the bottom of the menu, the middle (so you can see what's past and what's upcoming), or at the top (so that the menu acts like it's name). If I had to pick, I'd rank top, then middle, then bottom, as the best choices. Thoughts?

Thank you for all your hard work on this project!

**Comment by Araxeus** [comment]
I'm personally confused about this issue, don't really understand what you are experiencing

could you record a video?

**Comment by HanaNoAme** [comment]
I was going to create a new issue but I think this is the same feature I wanted to suggest. Right now the song queue (up next) is not dynamic, it doesn't scroll up or down by itself, so the song currently playing is often not visible unless you manually scroll down to it.

If you look at Spotify's song queue, you can see that the song currently playing is stickied at the top of the list. I think this is what @OnTheRocksBrew meant by top/middle/bottom: make the currently playing song always visible either by sticking it at the top or bottom, or making the list dynamically scroll down when the next song plays (or up when clicking previous, which is already the default behaviour).

This would be a really nice feature because it's a pain having to search the queue for the song currently playing every time I want to see what songs come after it.

**Comment by OnTheRocksBrew** [comment]
Yes, this is exactly, what I was referring to.

In my opinion, Up Next should have the current song at the top but, if memory serves, the list doesn’t seem to move as the songs finish playing.

Way back when, the Previous button seemed to display the behavior I’d expect so I was thinking that was actually the desired/correct behavior and that the list not auto scrolling after a song play was actually a bug.

**Comment by HanaNoAme** [comment]
The app still behaves the same way. If the song currently playing is below the visible part of the queue, clicking on previous scrolls the list down so that it's now visible. If you keep clicking previous, once the song currently playing becomes hidden again, this time above the queue, the list will scroll upwards so that the one at the top is the next in the queue.

None of these happen when clicking next or when a song ends and the next one plays.

I actually had no idea that the previous button behaved this way before reading your issue.. Shows how little I use it.
