### ISSUE TITLE
App regularly Locks Up

### ISSUE THREAD

**Issue by DrSuSE** [th-ch/youtube-music#746]
I use this mostly in the background while working, but did confirm this happens on both my office PC (Windows 10) and home PC (Windows 11).

After playing for a random about of time... sometimes a few minutes, sometimes almost an hour... the music stops and the app is unresponsive.  I notice that the taskbar title hadn't updated for a song or two (like it crashed a while ago and was just playing music it had already cached/downloaded).

How can I assist in troubleshooting?  I am using the latest version 1.17.

**Comment by Araxeus** [comment]
Are you using the portable version or did you install via the installer?

If you are using the portable then try installing https://github.com/th-ch/youtube-music/releases/download/v1.17.0/YouTube-Music-Setup-1.17.0.exe

Hopefully this is it, because its hard to pinpoint the origin of an unresponsive app (especially since this doesn't happen to most people)

**Comment by DrSuSE** [comment]
Sorry, I should've said I was using the installer version.
