### ISSUE TITLE
Advertisement plays when app is started (with adblock plugin enabled)

### ISSUE THREAD

**Issue by L3-NR** [th-ch/youtube-music#796]
When i start the app (for example after a computer restart), sometimes an advertisement plays (about the same frequency as if there was no adblock) before the last played song is played.
This may be due to the adblock plugin not being loaded in time?

**Comment by Araxeus** [comment]
Yes it's a known problem, apparently the adblocker doesn't load in time

I've tried fixing this myself, multiple times, but to no avail

**Comment by kotx** [comment]
Could we just work around it by triggering a reload when the adblocker plugin is first loaded?

**Comment by kotx** [comment]
Or just delay startup until all plugins are loaded :)

**Comment by Araxeus** [comment]
The sources are fetched on app launch, this *might* be the root of the problem

https://github.com/th-ch/youtube-music/blob/35bd62cc0d8856ed161bbd865255c88e15a08855/plugins/adblocker/blocker.js#L7-L14

If this is indeed the problem, we'll figure out a solution

**Comment by Araxeus** [comment]
I have an experimental faster adblocker here: https://github.com/Araxeus/youtube-music/tree/experimental-faster-adblocker

Looking for people to test it (I don't get any ads with it enabled, but that might be just luck since they are pretty rare for me)

**Comment by Zo-Bro-23** [comment]
> I have an experimental faster adblocker here: https://github.com/Araxeus/youtube-music/tree/experimental-faster-adblocker
> 
> Looking for people to test it (I don't get any ads with it enabled, but that might be just luck since they are pretty rare for me
> 
> @Zo-Bro-23

Sure, but what exactly are we looking for? Sometimes I do get ads the first time I load the app, but I seldom restart the app, and even then, it's pretty rare (only around 5 times since I started using the app).

It might be better to use Chrome DevTools to see if ads are being blocked, since without the adblocker, I get roughly one ad per song.

**Comment by Araxeus** [comment]
Just clone and build the branch and see if it blocks ads for you

**Comment by Zo-Bro-23** [comment]
> Just clone and build the branch and see if it blocks ads for you

Build available [here](https://github.com/Zo-Bro-23/youtube-music/releases/tag/v1.19.0) in case anyone needs it.

**Comment by Zo-Bro-23** [comment]
> I have an experimental faster adblocker here: https://github.com/Araxeus/youtube-music/tree/experimental-faster-adblocker
> 
> Looking for people to test it (I don't get any ads with it enabled, but that might be just luck since they are pretty rare for me
> 
> @Zo-Bro-23

Okay, so it takes a ***really*** long time (20-40 secs?) to load the song when the app starts, but now AD banner is shown as is seen with the other version. Switching to another song doesn't help. After this initial load time, the songs play pretty quickly, with a <1 sec delay for loading, which although noticeable, is not very annoying. Testing the other version (main release) again, the delay between songs is the same (0-1 secs), but the delay before the first song on load is much much less (1-2 secs instead of 20-40).

The new adblocker blocks ad, but the initial delay is really pronounced; any idea why that is? The whole point is to make loading faster, so I would recommend not switching adblockers until this issue is fixed.

**Comment by Araxeus** [comment]
Hmmm sorry it's really hard for me to work on this since I almost never get ads even without the adblocker

Something to do with my dns probably (or [portmaster](https://github.com/safing/portmaster), even tho I disabled it for youtube music for testing)

(btw this experimental adblocker loads way faster for me than the old (0.01 sec vs 1 sec+)

**Comment by Zo-Bro-23** [comment]
> btw this experimental adblocker loads way faster for me than the old (0.01 sec vs 1 sec+

Hmm, interesting. Why do you think it takes so long to load for me?
