### ISSUE TITLE
Background process consuming large amounts of ram and hard drive

### ISSUE THREAD

**Issue by bypequeno** [th-ch/youtube-music#81]
![image2324](https://user-images.githubusercontent.com/73602853/101225652-fed38480-365f-11eb-8282-bbdf16cda227.jpg)
It happens randomly, slowing down the other processes until it is finished by me. I had no idea why does it happen or something, I guess it is a bug with the auto update option. Also, the amount of ram it occupies is constantly increasing until it occupies all the available ram.

**Comment by th-ch** [comment]
Hey @bypequeno, thanks for the issue! It seems it does not happen on MacOS so it might be linked to the Windows version - you can disable auto-updates in options to see if it helps, otherwise disabling plugins might allow you to find the culprit (and find out if it's a plugin that's faulty or the app itself) - out of curiosity, so that I can try to reproduce, what plugins do you have enabled? And does it happen after a while or sometimes as soon as the app starts?

**Comment by bypequeno** [comment]
Hey bro, during the bug I had all the plugins enabled, but since some time ago that bug stopped coming out. I also realized that during the bug I didn't have the auto update option activated so I thinnk that is not the main problem. It happened to me three days in a row and then it stopped, but if it doesn't happen again I think the issue can be closed. Thanks.

**Comment by bypequeno** [comment]
It happened to me again today after one hour using it, you should take a look at the bug, it seems that it was not casual. Thanks for the work as well bro.
