### ISSUE TITLE
please add option to Auto cache songs for offline usage and data saving 

### ISSUE THREAD

**Issue by komals1** [th-ch/youtube-music#874]

**Comment by LetrixZ** [comment]
Welp, I failed. The app won't work without an internet connection and the streaming part is too tightly coupled for it to be feasible to do so, if even possible. Not even the official desktop web app offers that, only YouTube's main site.

**Comment by komals1** [comment]
there is app on android called ViMusic it does it beautifully ,

**Comment by LetrixZ** [comment]
The difference is that ViMusic is an app build around YouTube, while this is modifying the YouTube Music web app, and that way will let you go so far.

**Comment by Rednas83** [comment]
I would love to have this feature too. Perhaps add an option to make music available offline?
Something like:
![image](https://user-images.githubusercontent.com/25219229/235363895-43cb7c78-ca50-417c-a519-3c1dd7589dd6.png)

**Comment by LetrixZ** [comment]
> I would love to have this feature too. Perhaps add an option to make music available offline? Something like: ![image](https://user-images.githubusercontent.com/25219229/235363895-43cb7c78-ca50-417c-a519-3c1dd7589dd6.png)

As I explained before, it not possible to do it with this app and how it functions.
This is the YT Music website but with addons.

Another app,  that is independent from YT Music but that obtains its music from it should be made for this to work.

**Comment by Rednas83** [comment]
Are you 100% sure there is no way to trick YT music to play a song offline when the song is downloaded?

This is also possible with YT premium on mobile. You can download and play in Library>Downloads.
https://support.google.com/youtube/answer/6141269?hl=en&co=GENIE.Platform%3DAndroid#:~:text=In%20select%20areas%2C%20you%20can,becoming%20a%20YouTube%20Premium%20member.

**Comment by LetrixZ** [comment]
> Are you 100% sure there is no way to trick YT music to play a song offline when the song is downloaded?
> 
> This is also possible with YT premium on mobile. You can download and play in Library>Downloads. https://support.google.com/youtube/answer/6141269?hl=en&co=GENIE.Platform%3DAndroid#:~:text=In%20select%20areas%2C%20you%20can,becoming%20a%20YouTube%20Premium%20member.

That's because the mobile app was designed for that.

The idea here is to make the web app to work offline which it wont, it just won't load if there is no internet. 
You would need to make a fake app that works offline but that's a lot of work and at that point, just make a new app.

It might be possible that, if you have the song downloaded, to play the download instead of streaming it from YT servers, but it's a complex thing to achieve.

**Comment by Rednas83** [comment]
I agree that it's complex but It would be an awesome feature
* Play songs without internet/bad connection
* No need for another app to play songs offline
* More bandwith for other stuff
* Less tracking from YT/Google

Probably it will require
* Databases with all the downloaded songs incl path where it is downloaded
* Trigger to check if song is available offline
* Mechanism to play offline

**Comment by LetrixZ** [comment]
@Rednas83
One thing, offline access is impossible. You need internet to get the base website and the songs.

Playing downloaded songs instead of fetching them might be possible but I don't know if the main player can be used for that.

This is how that would work, assuming you can use the main player:
0. You manually download a playlist. 
1. Then when you play a song, the app would check on the database if it's downloaded, cut the connection to YT player and play the local file instead.
2. The song finishes, restores connection to proceed to next song. Start from 1.

**Comment by JellyBrick** [comment]
There is no way to cache YTM players. 
Even if it were possible, it would be a huge undertaking, equivalent to creating YTM from scratch.
