### ISSUE TITLE
Discord connection closed

### ISSUE THREAD

**Issue by Mixerr18** [th-ch/youtube-music#893]
reconnecting discord plugin 
![image](https://user-images.githubusercontent.com/80644911/203323669-6f41a327-812b-4f0b-9387-7b8d3733067e.png)

**Comment by juleast** [comment]
Having the same issue here. I tried restarting discord and then launching the yt music app but it gives me the same error.

**Comment by juleast** [comment]
Building the application manually seems to fix the issue. I just cloned the repository and navigated to the directory and then did `yarn` and `yarn start`

**Comment by Mixerr18** [comment]
> 

How did you that?

**Comment by juleast** [comment]
> Author

Just clone the repository and then navigate to that directory using the `cd` command. Also turns out building only works on mac I'm assuming because electron-builder fails on Windows for me. So the `yarn start` command just launches the application as is from what I know. If you go to the main page of this project the readme file has info on how to manually build or launch the project.

**Comment by juleast** [comment]
Ok, so it seems I was wrong about building. In an older [issue](https://github.com/th-ch/youtube-music/issues/848#issuecomment-1272520540), the dev commented on how to build for specific platform

**Comment by Mixerr18** [comment]
okay, thanks its work

**Comment by TheOnlyWayUp** [comment]
This is fixed in ee01ae1c00c73b0dfd5db8c6e7ff7352783987da, though not in a release yet, you can use the fixed version locally by cloning and `yarn build`ing, more information in #895.
