### ISSUE TITLE
Ad Blocker Wont work after fixing discord rpc status and building the app using node

### ISSUE THREAD

**Issue by Kazuto22** [th-ch/youtube-music#915]
so basically there was some errors with the app regarding the discord plugin and to fix that we needed to change the "ClientId" after that build the app using node and yarn cmds in windows terminal but after that the discord rpc status does work but the ad blocker don't work. after every song played there's add playing

**Comment by Zo-Bro-23** [comment]
![image](https://user-images.githubusercontent.com/62234360/206883070-554ce9bb-a420-4482-9b1e-4096ec12a5a1.png)

The adblocker plugin has not been updated since Jan 29 (ten months ago), so it is highly improbable that it stopped working with a recent update. Furthermore, it seems be working for the rest of us. Can you try building/using your previous version again, and seeing if the issue is present in that version too? Screenshots will be useful, especially side-by-side ones of both the versions (you can use the portable EXE for Windows, or try installing in different locations for other operating systems). Thanks!

**Comment by Kazuto22** [comment]
hey,
thanks for early reply, in latest version (1.8.0) the ad blocker does work without any issues however after seeing the post about discord rpc where you responded with a message describing the methods to change the discord "clientId" and rebuild it using node and yarn commands  

here's the screenshot of the modified version after editing the discord back.js and installing from "Dist" folder
![Untitled](https://user-images.githubusercontent.com/67105735/206884260-a52d5221-cc95-48ef-96a6-5a27361f8699.png)
