### ISSUE TITLE
Unable to start after building

### ISSUE THREAD

**Issue by ef1500** [th-ch/youtube-music#955]
Recently, I've been unable to open youtube music. I thought maybe it could have been Node.js or npm so I reinstalled them, and after rebuilding on a fresh install of both I am still greeted with the same error message:
Uncaught Exception:
SyntaxError: Unexpected token '
![image](https://user-images.githubusercontent.com/45581646/211361990-3433bfd8-e5ea-4e09-a926-1d9f4f8647a2.png)
I am using Windows 10, and this has been happening for about a month.
Any help would be greatly appreciated.

**Comment by Araxeus** [comment]
are you saying that this https://github.com/th-ch/youtube-music/releases/download/v1.19.0/YouTube-Music-Setup-1.19.0.exe works but when you clone and build yourself you get that error?

**Comment by ef1500** [comment]
It seems they both give me the same error. Running the setup file works fine, but running YouTube Music.exe is what throws the error. Both building locally and from the releases.

**Comment by Araxeus** [comment]
Very weird... works fine for me and I've never seen this happen

probably something to post as an issue in https://github.com/electron-userland/electron-builder
since we just specify that it should output a portable version

https://github.com/th-ch/youtube-music/blob/35bd62cc0d8856ed161bbd865255c88e15a08855/package.json#L37-L41

**Comment by ef1500** [comment]
Alright, I'll open an issue there, then. Thanks for your assistance!
