### ISSUE TITLE
RAM rises on v1.19.0

### ISSUE THREAD

**Issue by qtotter** [th-ch/youtube-music#958]
Windows 11 Pro 22H2/Core i5-8350U/RAM 12GB

I tried to download a playlist of 103 songs. The RAM useage before download was 3.7GB (31%), but it gradually rose to around 90% after 7 mins or so as download proceeded, and download just stopped nearly at the end after 101 songs. The download process was still running, and the RAM useage remained around 90% untill I terminated the app. It seems like a typical memory leak situation. Any thoughts? 

If I do the same download on Core i5-1035G1/RAM 24GB, its RAM useage went up to 14GB (59%) and stayed there after 101 songs untill I killed the app. It seems it was trying to download or encode the rest two songs, and some process internally hangs up?

Thx!

**Comment by Zo-Bro-23** [comment]
Does the issue persist with other versions of YTM (1.18, 1.17, etc) and other downloading tools like `youtube-dl`?

**Comment by qtotter** [comment]
I'm a newbie here, and I haven't tried any older builds. I'll come back to you when I reinstall an oler one or two. Thx!

**Comment by qtotter** [comment]
I tried 1.18, 1.17, but the results were the same altho RAM useage was slightly smaller than 1.19. Thx,

**Comment by Zo-Bro-23** [comment]
> I tried 1.18, 1.17, but the results were the same altho RAM useage was slightly smaller than 1.19. Thx,

Hmm. What about other tools like `youtube-dl`?

**Comment by TheBossMagnus** [comment]
> altho RAM useage was slightly smaller than 1.19. Thx

I can confirm, about 100 mb increase from 1.18 to 1.19

**Comment by qtotter** [comment]
> Hmm. What about other tools like `youtube-dl`?

Again, I'm a newbie with these things. YouTube-dl seems powerful, but I haven't gone through "how to use it" yet. YouTube-dl is just a downloader, and you have to encode downloaded files in your favorite format yourself, right?

I don't think the UI part of this app consumes tons of RAM itself, but it eats up RAM once it downloads songs, and never releases memory even after downloads are done...

**Comment by Zo-Bro-23** [comment]
See [here](http://ytdl-org.github.io/youtube-dl/download.html) for instructions to download `youtube-dl`. Then, run this command (if you're on Windows, open Command Prompt and navigate to the folder with the `youtube-dl.exe` file by running `cd FILE_PATH`):

```sh
youtube-dl --yes-playlist -x --audio-format mp3 --embed-thumbnail --add-metadata --postprocessor-args "-id3v2_version 3" --output "%(title)s.%(ext)s" --playlist-start NUMBER "PLAYLIST_URL"
```
Replace `NUMBER` with the playlist index to start from (use 1 if you're unsure about this) and `PLAYLIST_URL` with the playlist's URL.

This will download the playlist. The reason I'm asking you to do this is because I want to figure out if the issue pertinent to all youtube playlist downloaders or just the youtube-music application.
